### ISSUE TITLE
Possibility to set custom storageClass to AMQ broker

### ISSUE THREAD

**Issue by joonastikkanen** [rh-messaging/activemq-artemis-operator#47]
**Is your feature request related to a problem? Please describe.**
The clusters default storageClass is defined to slow storage and I want to use faster storage but operator doesn't seem to support it.

**Describe the solution you'd like**
I want to set my own storageClass in deploymentPlan to AMQ broker via yaml. 

for example: 
```yaml
spec:
  deploymentPlan:
    persistenceEnabled: true
    storage:
      size: 5G
      storageClassName: managed-premium
```
