### ISSUE TITLE
Possibility to set custom pod anti-affinity rules

### ISSUE THREAD

**Issue by noseka1** [rh-messaging/activemq-artemis-operator#49]
**Is your feature request related to a problem? Please describe.**
If we create a cluster of three AMQ brokers, we can see that two brokers were placed on the same OpenShift node.

**Describe the solution you'd like**
We would like to be able to define custom pod affinity/anti-affinity rules for the AMQ broker StatefulSet, so that we can spread the AMQ brokers across multiple OpenShift nodes or availability zones. Example:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker-ss
...
spec:
...
  template:
...
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: ActiveMQArtemis
                operator: In
                values: broker
            topologyKey: kubernetes.io/hostname
```

**Describe alternatives you've considered**
We don't have an alternative solution at the moment. If the scheduler places two AMQ brokers on the same node, we delete them and start over. Eventually, the scheduler will place the AMQ brokers on different nodes.

**Additional context**
We want to place the AMQ broker on separate nodes/availability zones to ensure availability.
